controller_list:
  - name: fake_right_hand_controller
    joints:
      - rh_THJ5
      - rh_THJ4
      - rh_THJ3
      - rh_THJ2
      - rh_THJ1
      - rh_thtip
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_FFtip
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
      - rh_MFtip
      - rh_RFJ4
      - rh_RFJ3
      - rh_RFJ2
      - rh_RFJ1
      - rh_RFtip
      - rh_LFJ5
      - rh_LFJ4
      - rh_LFJ3
      - rh_LFJ2
      - rh_LFJ1
      - rh_LFtip
      - rh_WRJ2
      - rh_WRJ1
  - name: fake_rh_manipulator_controller
    joints:
      []
  - name: fake_rh_first_finger_controller
    joints:
      []
  - name: fake_rh_first_finger_ee_controller
    joints:
      []
  - name: fake_rh_middle_finger_controller
    joints:
      []
  - name: fake_rh_middle_finger_ee_controller
    joints:
      []
  - name: fake_rh_ring_finger_controller
    joints:
      []
  - name: fake_rh_ring_finger_ee_controller
    joints:
      []
  - name: fake_rh_little_finger_controller
    joints:
      []
  - name: fake_rh_little_finger_ee_controller
    joints:
      []
  - name: fake_rh_thumb_controller
    joints:
      []
  - name: fake_rh_thumb_ee_controller
    joints:
      []
  - name: fake_rh_fingers_controller
    joints:
      []
