rh_first_finger:
  epsilon: 0.001
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_fftip
rh_middle_finger:
  epsilon: 0.001
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_mftip
rh_ring_finger:
  epsilon: 0.001
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_rftip
rh_little_finger:
  epsilon: 0.001
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_lftip
rh_thumb:
  epsilon: 0.001
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  lambda: 0.01
  maxIterations: 100
  tip_name: rh_thtip
right_hand:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  #kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  kinematics_solver_attempts: 1
  position_only_ik: true
  dtwist: 99999
  dpos: 0.001
  drot: 99999
